# Generated by Django 5.1.3 on 2024-12-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
