# Generated by Django 5.1.3 on 2024-12-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_answerlike_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlike',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
