# Generated by Django 5.1.3 on 2024-12-25 12:32

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='search_index',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
